[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RigidBodySim = "e61f16d8-a6b7-5689-8d03-627c2b27ebce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
